--- 
- hosts: 172.31.0.193
  become: yes  
  tasks:  
  - name: i wnt to execute direct linux
    command: hostname -f
    register: myresult
  - name: i want to display my first task result 
    debug: "{{myresult}}"