--- 
- hosts: all 
  become: true 
  tasks: 
  - name: install webserver on ansible node
    apt:
      name: apache2
      state: present  
  - name: i wnat to start webserver
    service:
      name: apache2
      state: started 