--- 
- hosts: all 
  become: true 
  tasks: 
  - name: install webserver on ansible node
    apt:
      name: apache2
      state: present 
    when: ansible_os_family ==  "Debian"   
  - name: i wnat to start webserver
    service:
      name: apache2
      state: stopped
    when: ansible_os_family ==  "Debian"
