--- 
- hosts: mywebservers 
  become: true 
  tasks: 
  - name: install webserver on ansible node
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present 
    when: ansible_os_family ==  "Debian"   
  - name: i wnat to start webserver
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family ==  "Debian"
  - name: i want to install webserver on ansible node
    dnf: 
      name: "{{mywebpackonredhat}}"
      state: installed
    when: ansible_os_family == "RedHat"
  - name: start httpd
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family == "RedHat"  
